project_name: cascadia

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    # remove README and LICENSE
    files:
      - none*

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

nfpms:
- maintainer: Tong Sun <suntong@cpan.org>
  description: CSS selector CLI tool
  homepage: https://github.com/suntong/cascadia
  license: MIT
  formats:
  - deb
  - rpm
  - apk
